### ISSUE TITLE
Unexpected errors with NPM run build

### ISSUE THREAD

**Issue by Vickysomtee** [jeanlescure/short-unique-id#62] opened 2024-05-13 09:54 UTC
Hiya.

We have been using this package on our nestjs application for while and everything has been working fine.

Lately we started getting these two errors in our docker `npm run build` process. We have upgraded to the latest version `5.2.0` and switched between node versions but the error still persists.

```
> npx @nestjs/cli build

src/core/utils/string-util.ts:110:35 - error TS2554: Expected 0 arguments, but got 1.

110     const uid = new ShortUniqueId({ length: 10 });
                                      ~~~~~~~~~~~~~~
src/core/utils/string-util.ts:111:16 - error TS2339: Property 'rnd' does not exist on type 'ShortUniqueId'.

111     return uid.rnd();
                   ~~~

Found 2 error(s).

```

**Comment by jeanlescure** [comment] 2024-05-30 02:29
Hi there @Vickysomtee , thanks for the report. This was probably introduced by the fix for #61 😮‍💨 

These are edge-cases where typings are not being representative of the actual code behavior.

I'll try and reproduce this error but would greatly appreciate if you could share a code example.

**Comment by jeanlescure** [comment] 2024-05-30 03:07
Been making modifications to the tsconfig in order to force the error to happen on the import specs, using tsc, to no avail.

Maybe this has to do with a specific version of Typescript used in the NestJS project, or a tsconfig enforced by NestJS.

No way to know without an example we can use to reproduce the error.

**Comment by Nabil-249** [comment] 2024-05-30 03:21
Hello, I have been also experiencing this issue with package (v5.2.0), here's the configuration to reproduce the issue:

tsconfig.json
```
{
    "compilerOptions": {
        "module": "NodeNext",
        "moduleResolution": "NodeNext",
        "target": "ES2022",
        "sourceMap": false,
        "outDir": "dist",
        "esModuleInterop": true,
        "allowSyntheticDefaultImports": true,
        "strict": true,
        "skipLibCheck": true,
        "noImplicitAny": true,
        "noUnusedLocals": true,
        "noUnusedParameters": true,
        "noUncheckedIndexedAccess": true,
    },
    "include": ["src/**/*"]
  }
```

sample_code.ts
```
import ShortUniqueId from 'short-unique-id';

//Property 'randomUUID' does not exist on type 'ShortUniqueId'.ts (2339)
const { randomUUID } = new ShortUniqueId();
```

**Comment by jeanlescure** [comment] 2024-05-31 03:52
I'm still being unable to reproduce this with the example you've shared @Nabil-249 

Could you share your package.json dependencies? I'm still wondering if it's a Typescript version issue.

**Comment by jeanlescure** [comment] 2024-05-31 04:05
I've just reverted to Typescript v4.9.5 and was able to reproduce the behavior.

I'm evaluating whether this should be prioritized given that the last v4 version of Typescript was released in January 2023 and there's been 20+ releases of v5 since then.

Would definitely be easier if Microsoft was less vague about Release and Support (i.e. EOL) schedules:

https://github.com/microsoft/TypeScript/issues/49088

**Comment by jeanlescure** [comment] 2024-05-31 04:09
I'll be following on fastify's footsteps here:

> To everyone coming here, typescript v4 is not supported by microsoft anymore, so please update your typescript to 5.0+

Source: https://github.com/fastify/fastify/issues/4873#issuecomment-1839196914

Closing this issue. If you see the same error with the latest version of Typescript feel free to open a new issue and include a reproduction repo 👍🏼

**Closed as completed** 2024-05-31 04:10 UTC
Labels: needs-reproduction-steps

**Comment by ugglr** [comment] 2024-06-06 11:57
If someone else faces this currently, I solved the same error by:
1. upgrading typescript to newest
2. setting target in `tsconfig` to `es2022`

**Comment by bacharuddinadieb** [comment] 2024-06-17 12:01
> If someone else faces this currently, I solved the same error by:
> 
> 1. upgrading typescript to newest
> 2. setting target in `tsconfig` to `es2022`

Yes, in my case i upgraded my typescript from 4.9.5 to the latest version (5.4.5) fixes the issue, thank you! :)
