### ISSUE TITLE
Error with Uglify

### ISSUE THREAD

**Issue by qgadrian** [jeanlescure/short-unique-id#1] opened 2017-06-07 14:06 UTC
Hi!

I was using your library but I had problems when using webpack, an Uglify error happens.

This is the output:

`ERROR in index_bundle.js from UglifyJs
TypeError: Cannot set property 'fixed' of undefined
    at TreeWalker.eval [as visit] (eval at <anonymous> (/Users/adrian/workspace/orbit/owner-app-web/node_modules/uglify-js/tools/node.js:27:1), <anonymous>:5581:25)
    at TreeWalker._visit (eval at <anonymous> (/Users/adrian/workspace/orbit/owner-app-web/node_modules/uglify-js/tools/node.js:27:1), <anonymous>:1339:24)
    at AST_This._walk (eval at <anonymous> (/Users/adrian/workspace/orbit/owner-app-web/node_modules/uglify-js/tools/node.js:27:1), <anonymous>:480:24)
    at AST_Dot.eval (eval at <anonymous> (/Users/adrian/workspace/orbit/owner-app-web/node_modules/uglify-js/tools/node.js:27:1), <anonymous>:1061:29)
    at TreeWalker._visit (eval at <anonymous> (/Users/adrian/workspace/orbit/owner-app-web/node_modules/uglify-js/tools/node.js:27:1), <anonymous>:1343:21)
    at AST_Dot._walk (eval at <anonymous> (/Users/adrian/workspace/orbit/owner-app-web/node_modules/uglify-js/tools/node.js:27:1), <anonymous>:1060:24)
    at AST_Dot.walk (eval at <anonymous> (/Users/adrian/workspace/orbit/owner-app-web/node_modules/uglify-js/tools/node.js:27:1), <anonymous>:483:21)
    at TreeWalker.eval [as visit] (eval at <anonymous> (/Users/adrian/workspace/orbit/owner-app-web/node_modules/uglify-js/tools/node.js:27:1), <anonymous>:5719:31)
    at TreeWalker._visit (eval at <anonymous> (/Users/adrian/workspace/orbit/owner-app-web/node_modules/uglify-js/tools/node.js:27:1), <anonymous>:1339:24)
    at AST_ForIn._walk (eval at <anonymous> (/Users/adrian/workspace/orbit/owner-app-web/node_modules/uglify-js/tools/node.js:27:1), <anonymous>:653:24)
    at walk_body (eval at <anonymous> (/Users/adrian/workspace/orbit/owner-app-web/node_modules/uglify-js/tools/node.js:27:1), <anonymous>:530:17)
    at AST_Function.eval (eval at <anonymous> (/Users/adrian/workspace/orbit/owner-app-web/node_modules/uglify-js/tools/node.js:27:1), <anonymous>:771:13)
    at eval (eval at <anonymous> (/Users/adrian/workspace/orbit/owner-app-web/node_modules/uglify-js/tools/node.js:27:1), <anonymous>:1340:21)
    at TreeWalker.eval [as visit] (eval at <anonymous> (/Users/adrian/workspace/orbit/owner-app-web/node_modules/uglify-js/tools/node.js:27:1), <anonymous>:5662:21)
    at TreeWalker._visit (eval at <anonymous> (/Users/adrian/workspace/orbit/owner-app-web/node_modules/uglify-js/tools/node.js:27:1), <anonymous>:1339:24)
    at AST_Function._walk (eval at <anonymous> (/Users/adrian/workspace/orbit/owner-app-web/node_modules/uglify-js/tools/node.js:27:1), <anonymous>:765:24)
    at AST_VarDef.eval (eval at <anonymous> (/Users/adrian/workspace/orbit/owner-app-web/node_modules/uglify-js/tools/node.js:27:1), <anonymous>:955:40)
    at eval (eval at <anonymous> (/Users/adrian/workspace/orbit/owner-app-web/node_modules/uglify-js/tools/node.js:27:1), <anonymous>:1340:21)
    at TreeWalker.eval [as visit] (eval at <anonymous> (/Users/adrian/workspace/orbit/owner-app-web/node_modules/uglify-js/tools/node.js:27:1), <anonymous>:5617:29)
    at TreeWalker._visit (eval at <anonymous> (/Users/adrian/workspace/orbit/owner-app-web/node_modules/uglify-js/tools/node.js:27:1), <anonymous>:1339:24)
    at AST_VarDef._walk (eval at <anonymous> (/Users/adrian/workspace/orbit/owner-app-web/node_modules/uglify-js/tools/node.js:27:1), <anonymous>:953:24)
    at AST_Var.eval (eval at <anonymous> (/Users/adrian/workspace/orbit/owner-app-web/node_modules/uglify-js/tools/node.js:27:1), <anonymous>:932:32)
    at TreeWalker._visit (eval at <anonymous> (/Users/adrian/workspace/orbit/owner-app-web/node_modules/uglify-js/tools/node.js:27:1), <anonymous>:1343:21)
    at AST_Var._walk (eval at <anonymous> (/Users/adrian/workspace/orbit/owner-app-web/node_modules/uglify-js/tools/node.js:27:1), <anonymous>:929:24)
    at walk_body (eval at <anonymous> (/Users/adrian/workspace/orbit/owner-app-web/node_modules/uglify-js/tools/node.js:27:1), <anonymous>:530:17)
    at AST_Function.eval (eval at <anonymous> (/Users/adrian/workspace/orbit/owner-app-web/node_modules/uglify-js/tools/node.js:27:1), <anonymous>:771:13)
    at eval (eval at <anonymous> (/Users/adrian/workspace/orbit/owner-app-web/node_modules/uglify-js/tools/node.js:27:1), <anonymous>:1340:21)
    at TreeWalker.eval [as visit] (eval at <anonymous> (/Users/adrian/workspace/orbit/owner-app-web/node_modules/uglify-js/tools/node.js:27:1), <anonymous>:5662:21)
    at TreeWalker._visit (eval at <anonymous> (/Users/adrian/workspace/orbit/owner-app-web/node_modules/uglify-js/tools/node.js:27:1), <anonymous>:1339:24)
    at AST_Function._walk (eval at <anonymous> (/Users/adrian/workspace/orbit/owner-app-web/node_modules/uglify-js/tools/node.js:27:1), <anonymous>:765:24)
`

**Comment by jeanlescure** [comment] 2017-06-07 22:34
Hi there @qgadrian!

As per your output I can corroborate that the error itself has to do with [uglifyjs](https://github.com/mishoo/UglifyJS/), you should totally let @mishoo know about this issue. As per [uglifyjs' README](https://github.com/mishoo/UglifyJS/blob/master/README.org#bugs), bug reports are done through [this Google group](http://groups.google.com/group/uglifyjs).

I'll keep this issue open. If you get the `uglifyjs` team to fix the problem just let me know. I'll more than gladly update the package and publish an update.

Cheers :v:

**Comment by qgadrian** [comment] 2017-06-08 09:32
Hi @jeanlescure, I don't have more information that the one I provided in this issue. I just moved on to another library that is not failing, but I wanted to let you know this is not working.

If you think it is really an issue with uglify and know what is going on, please let them know. I cannot open a bug without any information about it. 

Hope you understand.

Anyway, thanks for your reply!

**Comment by jeanlescure** [comment] 2017-06-08 14:20
Library is working properly on several projects including one using Webpack.

This seems to be an edge case. Tried to reproduce error, unable to.

Closing issue due to lack of detailed information on error and how to reproduce.

**Closed as completed by jeanlescure** 2017-06-08 14:20 UTC

**Comment by jeanlescure** [comment] 2017-12-29 17:29
@jeffturcotte provided insight as to the cause of the error (using any pre-1.0.0 version of uglifyjs-webpack-plugin and not uglify itself) and [the fix](https://github.com/jeanlescure/short-unique-id/pull/2).

Confirmed the bug by testing against `uglifyjs-webpack-plugin v0.4.6`.

Merged @jeffturcotte's pull request, bumped version and issued [release v1.1.1 on npmjs](https://www.npmjs.com/package/short-unique-id).
